name: Pull Requests
on: pull_request_target
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.2
        ports:
          - 27017:27017
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Run tests
        run: ./gradlew clean check --stacktrace
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto_assign.yml"
